/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    posts: Post;
    trails: Trail;
    influencers: Influencer;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    trails: TrailsSelect<false> | TrailsSelect<true>;
    influencers: InfluencersSelect<false> | InfluencersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('nl' | 'en') | ('nl' | 'en')[];
  globals: {
    'trail-labels': TrailLabel;
    'ui-labels': UiLabel;
  };
  globalsSelect: {
    'trail-labels': TrailLabelsSelect<false> | TrailLabelsSelect<true>;
    'ui-labels': UiLabelsSelect<false> | UiLabelsSelect<true>;
  };
  locale: 'nl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  logtoSub?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier. Use "home" for the home page.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * Background video
             */
            video: number | Media;
            headline: string;
            subheadline?: string | null;
            cta?:
              | {
                  /**
                   * Call-to-action button label.
                   */
                  ctaLabel?: string | null;
                  /**
                   * Call-to-action button URL or anchor.
                   */
                  ctaUrl?: string | null;
                  /**
                   * Appearance of the CTA button
                   */
                  outline?: boolean | null;
                  /**
                   * Optional icon shown left of the button label.
                   */
                  icon?:
                    | ('map-search' | 'group' | 'route' | 'clock' | 'hike' | 'prize' | 'camera' | 'terrain' | 'pets')
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title: string;
            /**
             * Used for internal linking using CTA buttons
             */
            sectionId: string;
            intro?: string | null;
            steps?:
              | {
                  icon?:
                    | ('map-search' | 'group' | 'route' | 'clock' | 'hike' | 'prize' | 'camera' | 'terrain' | 'pets')
                    | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'campaign-steps';
          }
        | {
            title: string;
            /**
             * Used for internal linking using CTA buttons
             */
            sectionId: string;
            intro?: string | null;
            /**
             * Select trails to be featured. Order determines display order.
             */
            trails?: (number | Trail)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'top-trails';
          }
        | {
            title: string;
            /**
             * Used for internal linking using CTA buttons
             */
            sectionId: string;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trails-overview';
          }
        | {
            title: string;
            /**
             * Used for internal linking using CTA buttons
             */
            sectionId: string;
            intro?: string | null;
            /**
             * Submit button label.
             */
            ctaLabel?: string | null;
            /**
             * Heading shown after a successful submission.
             */
            successTitle?: string | null;
            /**
             * Body text shown after a successful submission.
             */
            successMessage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'submit-trail';
          }
        | {
            title: string;
            /**
             * Used for internal linking using CTA buttons
             */
            sectionId: string;
            intro?: string | null;
            /**
             * Select blog posts to be featured. Order determines display order.
             */
            featuredPosts?: (number | Post)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog';
          }
        | {
            platform: 'instagram' | 'tiktok' | 'facebook';
            /**
             * Handle without the @ symbol.
             */
            handle: string;
            url: string;
            /**
             * e.g. "Join the community"
             */
            ctaText: string;
            /**
             * Optional section background image.
             */
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'social-button';
          }
        | {
            title: string;
            /**
             * Used for internal linking using CTA buttons
             */
            sectionId: string;
            intro?: string | null;
            /**
             * Select influencers to display.
             */
            influencers?: (number | Influencer)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'influencer-carousel';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trails".
 */
export interface Trail {
  id: number;
  title: string;
  published?: boolean | null;
  community?: boolean | null;
  header?: (number | null) | Media;
  photos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        url: string;
        type?: ('komoot' | 'allTrails' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Distance in kilometres.
   */
  distance?: number | null;
  /**
   * Duration in hours
   */
  duration?: number | null;
  difficulty?: ('easy' | 'moderate' | 'challenging') | null;
  /**
   * What are the off leash rules along this route.
   */
  offLeashArea?: ('fully' | 'partial' | 'none') | null;
  /**
   * Is there any hospitality nearby or on the route.
   */
  hospitality?: boolean | null;
  /**
   * Is there any accessible natural water on the route, like a river, lake or sea.
   */
  water?: boolean | null;
  /**
   * Trail start point for the map pin.
   */
  coordinates?: {
    /**
     * Latitude
     */
    lat?: number | null;
    /**
     * Longitude
     */
    lng?: number | null;
  };
  related?: {
    influencers?: (number | Influencer)[] | null;
    trails?: (number | Trail)[] | null;
    posts?: (number | Post)[] | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "influencers".
 */
export interface Influencer {
  id: number;
  name: string;
  image: number | Media;
  bio?: string | null;
  accounts: {
    platform: 'instagram' | 'facebook' | 'linkedin' | 'tiktok' | 'twitter' | 'youtube' | 'website';
    handle?: string | null;
    url: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * URL-friendly identifier, e.g. "trail-hero-of-the-week".
   */
  slug: string;
  title: string;
  /**
   * Short summary shown in blog block cards.
   */
  excerpt?: string | null;
  header?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  related?: {
    influencers?: (number | Influencer)[] | null;
    trails?: (number | Trail)[] | null;
    posts?: (number | Post)[] | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'trails';
        value: number | Trail;
      } | null)
    | ({
        relationTo: 'influencers';
        value: number | Influencer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  logtoSub?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              video?: T;
              headline?: T;
              subheadline?: T;
              cta?:
                | T
                | {
                    ctaLabel?: T;
                    ctaUrl?: T;
                    outline?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'campaign-steps'?:
          | T
          | {
              title?: T;
              sectionId?: T;
              intro?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'top-trails'?:
          | T
          | {
              title?: T;
              sectionId?: T;
              intro?: T;
              trails?: T;
              id?: T;
              blockName?: T;
            };
        'trails-overview'?:
          | T
          | {
              title?: T;
              sectionId?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        'submit-trail'?:
          | T
          | {
              title?: T;
              sectionId?: T;
              intro?: T;
              ctaLabel?: T;
              successTitle?: T;
              successMessage?: T;
              id?: T;
              blockName?: T;
            };
        blog?:
          | T
          | {
              title?: T;
              sectionId?: T;
              intro?: T;
              featuredPosts?: T;
              id?: T;
              blockName?: T;
            };
        'social-button'?:
          | T
          | {
              platform?: T;
              handle?: T;
              url?: T;
              ctaText?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        'influencer-carousel'?:
          | T
          | {
              title?: T;
              sectionId?: T;
              intro?: T;
              influencers?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  excerpt?: T;
  header?: T;
  content?: T;
  related?:
    | T
    | {
        influencers?: T;
        trails?: T;
        posts?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trails_select".
 */
export interface TrailsSelect<T extends boolean = true> {
  title?: T;
  published?: T;
  community?: T;
  header?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  content?: T;
  links?:
    | T
    | {
        url?: T;
        type?: T;
        id?: T;
      };
  distance?: T;
  duration?: T;
  difficulty?: T;
  offLeashArea?: T;
  hospitality?: T;
  water?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  related?:
    | T
    | {
        influencers?: T;
        trails?: T;
        posts?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "influencers_select".
 */
export interface InfluencersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  bio?: T;
  accounts?:
    | T
    | {
        platform?: T;
        handle?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-labels".
 */
export interface TrailLabel {
  id: number;
  difficulty?: {
    easy?: string | null;
    moderate?: string | null;
    challenging?: string | null;
    /**
     * Filter button label for showing all difficulties.
     */
    allDifficulties?: string | null;
  };
  offLeash?: {
    fully?: string | null;
    partial?: string | null;
    none?: string | null;
  };
  hospitality?: string | null;
  water?: string | null;
  /**
   * CTA button on trail cards.
   */
  viewTrail?: string | null;
  form?: {
    nameLabel?: string | null;
    emailLabel?: string | null;
    trailNameLabel?: string | null;
    descriptionLabel?: string | null;
    /**
     * Shown next to the description field label.
     */
    descriptionHint?: string | null;
    addressLabel?: string | null;
    distanceLabel?: string | null;
    offLeashAreaLabel?: string | null;
    offLeashAreaPlaceholder?: string | null;
    hospitalityLabel?: string | null;
    waterLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels".
 */
export interface UiLabel {
  id: number;
  /**
   * Back navigation button in the top bar.
   */
  back?: string | null;
  /**
   * Link text on blog post cards.
   */
  continueReading?: string | null;
  /**
   * Prefix for social follow button, e.g. "Follow on" → "Follow on Instagram".
   */
  followOn?: string | null;
  /**
   * Submit button label while a form is being submitted.
   */
  submitting?: string | null;
  /**
   * Overlay hint shown when scrolling the map without Ctrl (non-Mac).
   */
  mapZoomHint?: string | null;
  /**
   * Overlay hint shown when scrolling the map without ⌘ (Mac).
   */
  mapZoomHintMac?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-labels_select".
 */
export interface TrailLabelsSelect<T extends boolean = true> {
  difficulty?:
    | T
    | {
        easy?: T;
        moderate?: T;
        challenging?: T;
        allDifficulties?: T;
      };
  offLeash?:
    | T
    | {
        fully?: T;
        partial?: T;
        none?: T;
      };
  hospitality?: T;
  water?: T;
  viewTrail?: T;
  form?:
    | T
    | {
        nameLabel?: T;
        emailLabel?: T;
        trailNameLabel?: T;
        descriptionLabel?: T;
        descriptionHint?: T;
        addressLabel?: T;
        distanceLabel?: T;
        offLeashAreaLabel?: T;
        offLeashAreaPlaceholder?: T;
        hospitalityLabel?: T;
        waterLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ui-labels_select".
 */
export interface UiLabelsSelect<T extends boolean = true> {
  back?: T;
  continueReading?: T;
  followOn?: T;
  submitting?: T;
  mapZoomHint?: T;
  mapZoomHintMac?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}